### ISSUE TITLE
Login broken? 

### ISSUE THREAD

**Issue by StephenJPereira** [kesarion/letsenhance#1]
Hi, 

Is this CLI still working? 

I managed to install pretty easily (thanks for making it user-friendly), however it throws an error that the login information is incorrect even though it is. 

Thanks,

Stephen.

**Comment by kesarion** [comment]
@StephenJPereira  Hey, I haven't used this client in a long while, they may have changed the login url or disabled the previous login method entirely. I'll look into it when I have the time.

It seems they have an [API](http://help.letsenhance.io/en/articles/2550857-do-you-have-an-api) now, though it's still in closed beta. That would suggest they intend for clients to use the API instead of what I've done here. I might look into that as well, it may also be an option for you to look into, if they have an API, they might also have a command line utility or something like the client I've made here.

[Edit]
Oh, scratch that, they do indeed intend for people to use their new, [fancy API](https://business.letsenhance.io/). Look at the price of that thing! 😄

**Comment by StephenJPereira** [comment]
@kesarion thanks for your reply man! That sure does suck about the 99 dollar a month API :( 

I asked for API access before as I have an account with them and they emailed to say that access will be granted soon. Never got the access email in the end and now it's 99 dollars a month - yikes!

I think their days are numbered as this type of upscaling will be implemented by otheres in the near future - I'll wait it out for another solution or run my own AI script locally until then - nevertheless, thanks for everything :)
